export const reviewList = [
  {
    name: 'ハーレーダビッドソン相模原',
    image: './assets/img/sagamihara.jpeg',
    link: '//www.goobike.com/web/search/user_review.php?client_id=8500256',
    hoshi: 5.0,
    service: 'メンテナンス/定期点検',
  },
  {
    name: 'ガレージ９６',
    image: './assets/img/sagamihara.jpeg',
    link: '//www.goobike.com/web/search/user_review.php?client_id=8801335',
    hoshi: 4.5,
    service: 'メンテナンス/定期点検',
  },
  {
    name: 'ハーレーダビッドソン相模原',
    image: './assets/img/sagamihara.jpeg',
    link: '//www.goobike.com/web/search/user_review.php?client_id=8500256',
    hoshi: 3.0,
    service: 'メンテナンス/定期点検',
  },
  {
    name: 'SPーFOR',
    image: './assets/img/sagamihara.jpeg',
    link: '//www.goobike.com/web/search/user_review.php?client_id=8500665',
    hoshi: 5.0,
    service: 'メンテナンス/定期点検',
  },
  {
    name: 'SPーFOR',
    image: './assets/img/sagamihara.jpeg',
    link: '//www.goobike.com/web/search/user_review.php?client_id=8500665',
    hoshi: 5.0,
    service: 'メンテナンス/定期点検',
  },
  {
    name: 'ハーレーダビッドソン相模原',
    image: './assets/img/sagamihara.jpeg',
    link: '//www.goobike.com/web/search/user_review.php?client_id=8500256',
    hoshi: 5.0,
    service: 'メンテナンス/定期点検',
  },
  {
    name: 'ガレージ９６',
    image: './assets/img/sagamihara.jpeg',
    link: '//www.goobike.com/web/search/user_review.php?client_id=8801335',
    hoshi: 4.5,
    service: 'メンテナンス/定期点検',
  },
  {
    name: 'ハーレーダビッドソン相模原',
    image: './assets/img/sagamihara.jpeg',
    link: '//www.goobike.com/web/search/user_review.php?client_id=8500256',
    hoshi: 5.0,
    service: 'メンテナンス/定期点検',
  },
  {
    name: 'ハーレーダビッドソン相模原',
    image: './assets/img/sagamihara.jpeg',
    link: '//www.goobike.com/web/search/user_review.php?client_id=8500256',
    hoshi: 5.0,
    service: 'メンテナンス/定期点検',
  },
  {
    name: 'ハーレーダビッドソン相模原',
    image: './assets/img/sagamihara.jpeg',
    link: '//www.goobike.com/web/search/user_review.php?client_id=8500256',
    hoshi: 5.0,
    service: 'メンテナンス/定期点検',
  },
  {
    name: 'ハーレーダビッドソン相模原',
    image: './assets/img/sagamihara.jpeg',
    link: '//www.goobike.com/web/search/user_review.php?client_id=8500256',
    hoshi: 5.0,
    service: 'メンテナンス/定期点検',
  },
  {
    name: 'ハーレーダビッドソン相模原',
    image: './assets/img/sagamihara.jpeg',
    link: '//www.goobike.com/web/search/user_review.php?client_id=8500256',
    hoshi: 5.0,
    service: 'メンテナンス/定期点検',
  },
  {
    name: 'ハーレーダビッドソン相模原',
    image: './assets/img/sagamihara.jpeg',
    link: '//www.goobike.com/web/search/user_review.php?client_id=8500256',
    hoshi: 5.0,
    service: 'メンテナンス/定期点検',
  },
  {
    name: 'ハーレーダビッドソン相模原',
    image: './assets/img/sagamihara.jpeg',
    link: '//www.goobike.com/web/search/user_review.php?client_id=8500256',
    hoshi: 5.0,
    service: 'メンテナンス/定期点検',
  },
  {
    name: 'ハーレーダビッドソン相模原',
    image: './assets/img/sagamihara.jpeg',
    link: '//www.goobike.com/web/search/user_review.php?client_id=8500256',
    hoshi: 5.0,
    service: 'メンテナンス/定期点検',
  },
  {
    name: 'ハーレーダビッドソン相模原',
    image: './assets/img/sagamihara.jpeg',
    link: '//www.goobike.com/web/search/user_review.php?client_id=8500256',
    hoshi: 5.0,
    service: 'メンテナンス/定期点検',
  },
];