export const sagyouzisseki = [
  {
    cont: '修理',
    maker: 'ホンダ',
    syasyu: 'NSR250R SE',
    messe: 'ホンダ　NSR250R MC21 2台の不動車輪　赤いNSR',
    price: 220000,
    name: 'I•C•U',
    image: './assets/img/sagamihara.jpeg',
    storeLink: 'https://www.goobike.com/web/search/shop_blog.php?client_id=8800275',
    menteLink: '/after/work/21508',
  },
  {
    cont: '修理/カスタム',
    maker: 'ハーレーダビッドソン',
    syasyu: 'FLHTCUTG トライグ',
    messe: 'FLHTCUTG トライグライドウルトラ　トライク　カスタム　ミルウ',
    price: 25300,
    name: '（株）バイクプラザヤマノ',
    image: './assets/img/sagamihara.jpeg',
    storeLink: 'https://www.goobike.com/web/search/shop_blog.php?client_id=8800585',
    menteLink: '/after/work/21467',
  },
  {
    cont: '修理/カスタム',
    maker: 'ハーレーダビッドソン',
    syasyu: 'FLHTCUTG トライグ',
    messe: 'FLHTCUTG トライグライドウルトラ　トライク　カスタム　ミルウ',
    price: 25300,
    name: '（株）バイクプラザヤマノ',
    image: './assets/img/sagamihara.jpeg',
    storeLink: 'https://www.goobike.com/web/search/shop_blog.php?client_id=8800585',
    menteLink: '/after/work/21467',
  },
  {
    cont: '修理/カスタム',
    maker: 'ハーレーダビッドソン',
    syasyu: 'FLHTCUTG トライグ',
    messe: 'FLHTCUTG トライグライドウルトラ　トライク　カスタム　ミルウ',
    price: 25300,
    name: '（株）バイクプラザヤマノ',
    image: './assets/img/sagamihara.jpeg',
    storeLink: 'https://www.goobike.com/web/search/shop_blog.php?client_id=8800585',
    menteLink: '/after/work/21467',
  },
  {
    cont: '修理/カスタム',
    maker: 'ハーレーダビッドソン',
    syasyu: 'FLHTCUTG トライグ',
    messe: 'FLHTCUTG トライグライドウルトラ　トライク　カスタム　ミルウ',
    price: 25300,
    name: '（株）バイクプラザヤマノ',
    image: './assets/img/sagamihara.jpeg',
    storeLink: 'https://www.goobike.com/web/search/shop_blog.php?client_id=8800585',
    menteLink: '/after/work/21467',
  },
  {
    cont: '修理/カスタム',
    maker: 'ハーレーダビッドソン',
    syasyu: 'FLHTCUTG トライグ',
    messe: 'FLHTCUTG トライグライドウルトラ　トライク　カスタム　ミルウ',
    price: 25300,
    name: '（株）バイクプラザヤマノ',
    image: './assets/img/sagamihara.jpeg',
    storeLink: 'https://www.goobike.com/web/search/shop_blog.php?client_id=8800585',
    menteLink: '/after/work/21467',
  },
  {
    cont: '修理/カスタム',
    maker: 'ハーレーダビッドソン',
    syasyu: 'FLHTCUTG トライグ',
    messe: 'FLHTCUTG トライグライドウルトラ　トライク　カスタム　ミルウ',
    price: 25300,
    name: '（株）バイクプラザヤマノ',
    image: './assets/img/sagamihara.jpeg',
    storeLink: 'https://www.goobike.com/web/search/shop_blog.php?client_id=8800585',
    menteLink: '/after/work/21467',
  },
  {
    cont: '修理/カスタム',
    maker: 'ハーレーダビッドソン',
    syasyu: 'FLHTCUTG トライグ',
    messe: 'FLHTCUTG トライグライドウルトラ　トライク　カスタム　ミルウ',
    price: 25300,
    name: '（株）バイクプラザヤマノ',
    image: './assets/img/sagamihara.jpeg',
    storeLink: 'https://www.goobike.com/web/search/shop_blog.php?client_id=8800585',
    menteLink: '/after/work/21467',
  },
  {
    cont: '修理/カスタム',
    maker: 'ハーレーダビッドソン',
    syasyu: 'FLHTCUTG トライグ',
    messe: 'FLHTCUTG トライグライドウルトラ　トライク　カスタム　ミルウ',
    price: 25300,
    name: '（株）バイクプラザヤマノ',
    image: './assets/img/sagamihara.jpeg',
    storeLink: 'https://www.goobike.com/web/search/shop_blog.php?client_id=8800585',
    menteLink: '/after/work/21467',
  },
]